GeneralCMS/GeneralCMS.Admin/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeneralCMS.Admin.ViewComponents
{
    public class HeaderViewComponent: BaseViewComponent
    {
        public override IViewComponentResult Invoke()
        {
            return View(CurrentUser);
        }
    }
}

GeneralCMS/GeneralCMS.Admin/ViewComponents/LeftSidebarViewComponent.cs
using GeneralCMS.Models.ViewModel.Admin;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace GeneralCMS.Admin.ViewComponents
{
    public class LeftSidebarViewComponent : BaseViewComponent
    {
        private readonly IMemoryCache memoryCache;
        public LeftSidebarViewComponent(IMemoryCache memoryCache)
        {
            this.memoryCache = memoryCache;
        }

        public override IViewComponentResult Invoke()
        {
            VSidebarMenu menus = new VSidebarMenu(); 
            menus.User = CurrentUser;
            
            List<VMenu> cache;
            if (!memoryCache.TryGetValue(VSidebarMenu.menusKey, out cache))
            {
                //首次启动，会加载菜单,然后保存到内存中
                menus.Menus = GetMenus();
                //设置缓存回收优先级 （程序压力大时，会根据优先级自动回收）
                memoryCache.Set(VSidebarMenu.menusKey, menus.Menus, new MemoryCacheEntryOptions().SetPriority(CacheItemPriority.High));
            }
            else
            {
                menus.Menus = cache;
            } 
            return View(menus);
        }

        private List<VMenu> GetMenus()
        {
            List<VMenu> res = new List<VMenu>();
            VMenu menu = new VMenu("首页", "fa-home", "/Home/Welcome");
            res.Add(menu);

            menu = new VMenu("内容管理", "fa-window-restore", "#");
            menu.Childs.Add(new VMenu("分类管理", "fa-picture-o", "/PageMng/Setting1"));
            menu.Childs.Add(new VMenu("文章管理", "fa-picture-o", "/PageMng/Slideshow2"));
            menu.Childs.Add(new VMenu("招聘管理", "fa-picture-o", "/PageMng/Navigation3"));
            menu.Childs.Add(new VMenu("单页管理", "fa-file-text-o", "/PageMng/Friendlink4"));
            res.Add(menu);

            menu = new VMenu("页面管理", "fa-window-restore", "#");
            menu.Childs.Add(new VMenu("轮播图管理", "fa-picture-o", "/PageMng/Slideshow"));
            menu.Childs.Add(new VMenu("导航管理", "fa-picture-o", "/PageMng/Navigation"));
            menu.Childs.Add(new VMenu("友情链接", "fa-file-text-o", "/PageMng/Friendlink"));
            res.Add(menu);

            menu = new VMenu("系统管理", "fa-cogs", "#"); 
            menu.Childs.Add(new VMenu("管理员", "fa-users", "/SystemMng/UserList"));
            menu.Childs.Add(new VMenu("系统设置", "fa-cog", "/SystemMng/Setting"));
            menu.Childs.Add(new VMenu("操作日志", "fa-file-text-o", "/SystemMng/Logs"));
            res.Add(menu);

            return res;
        }
    }
}

GeneralCMS/GeneralCMS.Admin/Views/Shared/_ContextLayout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - 管理后台</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="author" content="Lio.Huang">
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/lib/admin-lte/dist/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/lib/admin-lte/dist/css/skins/_all-skins.css" rel="stylesheet" />
    <link href="~/lib/PACE/themes/green/pace-theme-minimal.css" rel="stylesheet" />
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />

    <link href="~/css/contextBase.css" rel="stylesheet" />
    @RenderSection("header", required: false)

</head>
<body>

    @RenderBody()


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/admin-lte/dist/js/adminlte.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/common.js"></script>
    <script>
        toastr.options = {
            closeButton: false,
            debug: false,
            progressBar: true,
            positionClass: "toast-top-center",
            onclick: null,
            showDuration: "300",
            hideDuration: "1000",
            timeOut: "2000",
            extendedTimeOut: "1000",
            showEasing: "swing",
            hideEasing: "linear",
            showMethod: "fadeIn",
            hideMethod: "fadeOut"
        };
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

GeneralCMS/GeneralCMS.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - 管理后台</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="author" content="Lio.Huang">
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/lib/admin-lte/dist/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/lib/admin-lte/dist/css/skins/_all-skins.css" rel="stylesheet" />
    <link href="~/lib/PACE/themes/green/pace-theme-minimal.css" rel="stylesheet" />
    @RenderSection("header", required: false)

</head>
<body class="hold-transition sidebar-mini fixed">
    <div class="wrapper">
        <!-- Main Header -->
        @await Component.InvokeAsync("Header")

        <!-- 左侧导航 徽标和侧栏 -->
        @await Component.InvokeAsync("LeftSidebar")

        <!-- 内容 -->
        <div class="content-wrapper">
            @RenderBody()
        </div>

        <!-- 页脚 -->
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                Anything you want
            </div>
            <strong>
                <script>document.write(new Date().getFullYear());</script> Banana科技股份公司
            </strong>- Colorlib All rights reserved
        </footer>

        <div class="control-sidebar-bg"></div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/admin-lte/dist/js/adminlte.min.js"></script>
    <script src="~/js/sidebarskins.js" charset="gbk"></script>
    <script src="~/lib/PACE/pace.min.js"></script>
    <script src="~/js/loadpartial.js"></script>
    <script src="~/js/common.js"></script>
    <script type="text/javascript">
        $.loadPartial();
    </script>
    <script>
        $(function () {
            //adminlte 左侧边栏菜单点击效果
            $('.sidebar-menu li > a').on('click', function () {
                var $parent = $(this).parent().addClass('active');
                $parent.siblings().removeClass('active');
                var otherchild = $parent.siblings('.treeview.menu-open').removeClass('menu-open');
                otherchild.find(".treeview-menu li").removeClass('active');
            });

            $('.sidebar-menu a').each(function () {
                //父级刷新也可以高亮
                if (this.href === window.location.href.replace("/#", "")) {
                    $(this).parent().addClass('active')
                        .closest('.treeview-menu').addClass('.menu-open').siblings().removeClass('active')
                        .closest('.treeview').addClass('active').siblings().removeClass('active');
                }
                if (window.location.pathname == "/" && window.location.hash=="") {
                    $('.sidebar-menu a').first().parent().addClass('active');
                }
            });
        });

        $(document).ajaxStart(function () {
            Pace.restart();
        });

    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>