GeneralCMS/GeneralCMS.Web/ViewComponents/FooterViewComponent.cs
using GeneralCMS.Application.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeneralCMS.Web.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly IHomeService homeService;
        public FooterViewComponent(IHomeService homeService)
        {
            this.homeService = homeService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var data = await Task.FromResult(homeService.GetVFooterPageData());
            return View(data);
        }
    }
}

GeneralCMS/GeneralCMS.Web/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GeneralCMS.Application.Services;
using GeneralCMS.Models.ViewModel;

namespace GeneralCMS.Web.Components
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly IHomeService homeService;
        public HeaderViewComponent(IHomeService homeService)
        {
            this.homeService = homeService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var data = await Task.FromResult(homeService.GetVHeaderPageData());
            return View(data);
        }
    }
}

GeneralCMS/GeneralCMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>欢迎您访问 @ViewData["Title"]</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="author" content="Lio.Huang">
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />

    <link href="~/css/base.css" rel="stylesheet" />
    <link href="~/css/common/header.css" rel="stylesheet" />
    <link href="~/css/common/footer.css" rel="stylesheet" />
    <link href="~/css/common/breadcumb.css" rel="stylesheet" />
    @RenderSection("header", required: false)

</head>
<body>

    @await Component.InvokeAsync("Header")

    @RenderBody()

    @await Component.InvokeAsync("Footer")
    <!-- jQuery-2.2.4 js -->
    <script src="~/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/js/bootstrap/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="~/js/bootstrap/bootstrap.min.js"></script>
    <!-- All Plugins js -->
    <script src="~/js/plugins/plugins.js"></script>
    <!-- Active js -->
    <script src="~/js/active.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

GeneralCMS/GeneralCMS.Web/Views/Shared/_PageView.cshtml
@model GeneralCMS.Models.ViewModel.Frontend.VPageViewInfo

<nav aria-label="Page navigation mb-30 ">
    <ul class="pagination">
        @{
            var pageMin = (Model.pageNo - 2) > 0 ? (Model.pageNo - 2) : 1;
            var pageMax = (Model.pageNo + 2) > Model.pageCount ? Model.pageCount : (Model.pageNo + 2);
            int nextPage = Model.pageNo + 1;
            int perPage = Model.pageNo - 1;
            if (Model.pageCount > 1)
            {
                if (Model.pageNo == 1)
                {
                    pageMax = 5;
                    for (int ipagenum = pageMin; ipagenum <= pageMax; ipagenum++)
                    {
                        if (ipagenum == Model.pageNo)
                        {
                            <li class="page-item"><a class="page-link pagination-active">@ipagenum</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="@Model.PerUrl?navId=@Model.NavigationId&pageNum=@ipagenum&pageSize=@Model.pageSize">@ipagenum</a></li>
                        }
                    }
                    <li class="page-item"><a class="page-link" href="@Model.PerUrl?navId=@Model.NavigationId&pageNum=@nextPage&pageSize=@Model.pageSize"><i class="fa fa-angle-right"></i></a></li>
                    <li class="page-item"><a class="page-link" href="@Model.PerUrl?navId=@Model.NavigationId&pageNum=@Model.pageCount&pageSize=@Model.pageSize"><i class="fa fa-angle-double-right"></i></a></li>

                }
                else
                {
                    if (Model.pageCount == Model.pageNo)
                    {
                        pageMin = Model.pageNo - 4;
                    }
                    if (Model.pageNo - 2 > 1)
                    {
                        <li class="page-item"><a class="page-link" href="@Model.PerUrl?navId=@Model.NavigationId&pageNum=1&pageSize=@Model.pageSize"><i class="fa fa-angle-double-left"></i></a></li>
                        <li class="page-item"><a class="page-link" href="@Model.PerUrl?navId=@Model.NavigationId&pageNum=@perPage&pageSize=@Model.pageSize"><i class="fa fa-angle-left"></i></a></li>
                    }
                    for (int ipagenum = pageMin; ipagenum <= pageMax; ipagenum++)
                    {
                        if (ipagenum == Model.pageNo)
                        {
                            <li class="page-item"><a class="page-link pagination-active">@ipagenum</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="@Model.PerUrl?navId=@Model.NavigationId&pageNum=@ipagenum&pageSize=@Model.pageSize">@ipagenum</a></li>
                        }
                    }
                    if (Model.pageNo + 2 < Model.pageCount)
                    {
                        <li class="page-item"><a class="page-link" href="@Model.PerUrl?navId=@Model.NavigationId&pageNum=@nextPage&pageSize=@Model.pageSize"><i class="fa fa-angle-right"></i></a></li>
                        <li class="page-item"><a class="page-link" href="@Model.PerUrl?navId=@Model.NavigationId&pageNum=@Model.pageCount&pageSize=@Model.pageSize"><i class="fa fa-angle-double-right"></i></a></li>
                    }
                }
            }
            else
            {
                <li class="page-item"><a class="page-link pagination-active" href="@Model.PerUrl?navId=@Model.NavigationId&pageNum=@Model.pageNo&pageSize=@Model.pageSize">1</a></li>
            }
        }
    </ul>
</nav>