GeneralCMS/GeneralCMS.Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GeneralCMS.Application.Services;
using Microsoft.AspNetCore.Mvc;

namespace GeneralCMS.Web.Controllers
{
    public class ContactController : Controller
    {
        private readonly IOwnerService ownerService;
        public ContactController(IOwnerService ownerService)
        {
            this.ownerService = ownerService;
        }

        public async Task<IActionResult> Index(int navId)
        {
            var data =await ownerService.GetContactInfo();
            data.NavigationId = navId;
            return View(data);
        } 
    }
}

GeneralCMS/GeneralCMS.Web/ViewComponents/BreadcrumbViewComponent.cs
using GeneralCMS.Application.Services;
using GeneralCMS.Models.ViewModel.Frontend;
using GeneralCMS.Models.Enum;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GeneralCMS.Models.Dto;

namespace GeneralCMS.Web.ViewComponents
{
    public class BreadcrumbViewComponent : ViewComponent
    {
        private readonly IHomeService homeService;
        public BreadcrumbViewComponent(IHomeService homeService)
        {
            this.homeService = homeService;
        }

        public async Task<IViewComponentResult> InvokeAsync(int navId)
        {
            VBreadcrumb breadcrumb;
            if (navId == 0)
            {
                return View(new VBreadcrumb("", "", "#"));
            }
            var nav = homeService.GetNavigationsAsync(navId);
            var img = await Task.FromResult(homeService.GetImgPlaysAsync(navId, EImageType.Header));
            var navRes = nav.Result;
            var imgRes = img.Result.FirstOrDefault() ?? new ImgPlayDto();
            if (nav.Result.ParentId > 0)
            {
                var navParent = await Task.FromResult(homeService.GetNavigationsParentAsync(navId));
                var navParentRes = navParent.Result;
                breadcrumb = new VBreadcrumb(navRes.Name, navParentRes.Name, navParentRes.Url, imgRes.ImgUrl);
            }
            else
            {
                breadcrumb = new VBreadcrumb(navRes.Name, navRes.Name, navRes.Url, imgRes.ImgUrl);
            }
            return View(breadcrumb);
        }
    }
}

GeneralCMS/GeneralCMS.Web/Views/Contact/Index.cshtml
@model GeneralCMS.Models.ViewModel.Frontend.VContactInfo
@{
    ViewData["Title"] = "联系我们";
}

@section header{
    <link href="~/css/contact/list.css" rel="stylesheet" />
}

@await Component.InvokeAsync("Breadcrumb", Model.NavigationId)

<div class="container">
    <div class="row mb-30">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
            <iframe width='100%' height='330' frameborder='0' scrolling='no' marginheight='0' marginwidth='0' src='@Model.Owner.MapIFrameUrl'></iframe>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 contact-area">
            <h5>@Model.Owner.Name</h5>
            <p>联系人：@Model.Owner.LinkMan</p>
            <p>联系电话：@Model.Owner.Mobile</p>
            <p>联系邮箱：@Model.Owner.Email</p>
            <p>公司详细地址：@Model.Owner.Address</p>
        </div>
    </div>
</div>